logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %highlight(%48.48logger) - %msg%n"
  level:
    "[de.workshops.bookdemo]": debug
    
spring:
  thymeleaf:
    enabled: true
    suffix: .ty

myapp:
  param1: value
  param2: 42
  inner:
    innerParam1: Test

---
spring:
  config:
    activate:
      on-profile:
      - prod
      
server:
  port: 8081