spring:
  thymeleaf:
    enabled: true
    suffix: .ty

  datasource:
    url: jdbc:h2:./bookDB;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    
  sql:
    init:
      mode: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    
  h2:
    console:
      enabled: true

  security:
    user:
      name: user
      password: pass 

    oauth2:
      client:
        registration:
          google:
            # client mit redirect-uri *:8080 und *:8081
            client-id: 148971885543-co9dv22tjamh7amdonnqod69dsd721rp.apps.googleusercontent.com
            client-secret: mXAtT6Ze7M7mK_KCb5VEyJSY       

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8888
        username: todo42
        password: v9K43$8q704$uXLc
        instance:
          name: bookdemo
          management-base-url: http://localhost:8080
          service-base-url: http://localhost:8080
          metadata:
            user.name: alice
            user.password: pass


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

      
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{username}] %highlight(%-5level) %highlight(%48.48logger) - %msg%n"
  level:
    "[de.workshops.bookdemo]": debug
    "[org.hibernate.SQL]": info
    "[org.hibernate.type]": info
    "[org.jooq]": debug
    "[org.springframework.security]": debug
    "[org.springframework.web]": debug

myapp:
  param1: value
  param2: 42
  inner:
    innerParam1: Test

---
spring:
  config:
    activate:
      on-profile:
      - prod
      
server:
  port: 8081