spring:
  thymeleaf:
    enabled: true
    suffix: .ty

  datasource:
    url: jdbc:h2:./bookDB;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    
  sql:
    init:
      mode: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %highlight(%48.48logger) - %msg%n"
  level:
    "[de.workshops.bookdemo]": debug
    "[org.hibernate.SQL]": debug
    "[org.hibernate.type]": trace
    "[org.jooq]": debug
    

myapp:
  param1: value
  param2: 42
  inner:
    innerParam1: Test

---
spring:
  config:
    activate:
      on-profile:
      - prod
      
server:
  port: 8081